In [20]:
#NumPyをインポート
import numpy as np

#「多次元配列」を書く
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

#行列演算（積の計算）
np.dot(A, B)
print(np.dot(A, B))

#配列の操作(計算された行列の要素の最大値を求めて表示する)
np.dot(A, B).max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47